### ISSUE TITLE
VowpalWabbit flags on the labels

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/coba#2]
Hi,

thanks for great project!

Is it possible to add vw flags to plot labels?

Right now I am seeing that kind of plot:
![image](https://user-images.githubusercontent.com/41013086/110150259-0adcf880-7dad-11eb-9e6c-4d430d11e2d0.png)

when I am doing something like this:
```
    learner_factories = [
        VowpalLearner(epsilon=0.2, seed=10, flags=''),
        VowpalLearner(epsilon=0.2, seed=10, flags='--coin')
        ]
    benchmark.evaluate(learner_factories).standard_plot()
```
and it is hard to correlate plots with configurations.

**Comment by mrucker** [comment]
Glad you like it. I can totally do that. I'll commit and release an update for it today. 

Also, just so you know, since we last talked I released an update for COBA that's got a lot of new features which make it easier to add custom extensions to benchmarks. I'll be adding more complete documentation for the new stuff in the next few weeks.

**Comment by mrucker** [comment]
Commit aa2c2a8f0fcd3c515de17c62e14403c565dec570 contains this improvement. I've also released this to PyPi in version 2.2.1.

**Comment by mrucker** [comment]
(or if you want to do it yourself in your own fork you can change the following method in VowpalLearner.)

  ```
class VowpalLearner:
    ...
    @property
    def params(self) -> Dict[str, Any]:

        params = {**self._learning.params(), **self._exploration.params()}
 
        if self._flags != '':
            params['flags'] = self._flags
  
        return params
```

**Comment by ataymano** [comment]
thank you for quick response!
